export const GET_RESOURCE_START = "GET_RESOURCE_START";
export const GET_RESOURCE_FAILED = "GET_RESOURCE_FAILED";
export const GET_PROVIDES_SUCCESS = "GET_PROVIDES_SUCCESS";
export const GET_DISTRICTS_SUCCESS = "GET_DISTRICTS_SUCCESS";
export const GET_WARDS_SUCCESS = "GET_WARDS_SUCCESS";
export const GET_LANDING_SUCCESS = "GET_LANDING_SUCCESS";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
